
.PHONY: all say_hello generate clean

all : say_hello generate
say_hello:
	@echo "Hello world"



generate:
	@echo "Creatin empty text files..."
	touch file-{1..10}.txt


clean:
	@echo "cleaning up..."
	rm *.txt
